### ISSUE TITLE
What is your opinion on Dart?

### ISSUE THREAD

**Issue by tenhobi** [Widdershin/ama#11]
Dart can be used on web (compiled to JS via Dart2JS, [AngularDart](https://webdev.dartlang.org/angular/), ...), mobile ([Flutter](https://flutter.io/)), server etc.

Have you ever tried it, maybe as alternative to Javascript? What is your opinion on this language and it's platform? :-)

**Comment by Widdershin** [comment]
Hey sorry I never got around to answering this!

I've never tried Dart, and haven't really looked into it much. Prior to the existence of TypeScript/Flow, I had the impression that it was one of the better way to get a static type system for clientside development.

Should I look into Dart? Are you a fan?

**Comment by tenhobi** [comment]
I am a fan of Dart and I do recomment you to take a look at it. Especially take look at Flutter (and AngularDart) – awesome technologies around it.
