### ISSUE TITLE
Do you ever get imposter syndrome? Why? What do you do to evade it?

### ISSUE THREAD

**Issue by sindresorhus** [Widdershin/ama#2]

**Comment by Widdershin** [comment]
I used to get a lot of imposter syndrome. For the first 4 - 5 years or so of my coding career I didn't consider myself to be a 'real developer'. Looking back, that's totally not how I think about it.

It comes in a few different forms for me:
- Feeling like I'm not good enough to understand a particular technology (FP, SQL, the web, C, etc)
- Feeling like I'm undeserving of the respect of the people around me
- Feeling like my work is inconsequential

I actually had a bout of imposter syndrome when I considered forking your ama repo and making a pull request. I looked at the list of names of influential developers, and I told myself I wasn't good enough.

At the time, I thought about that for a second, laughed and then did it anyway. I find the best remedy for me is to do my best to overcome the feeling and carry on with what I want regardless. 

Something else that helped hugely was attending a coding bootcamp, Enspiral Dev Academy. I was one of two people in my cohort with prior coding experience, everyone else was brand new. I dedicated myself to working with and helping the new members of my cohort as much as possible. That helped me understand just how much I actually do know and how much value I can bring to others. I think teaching is a great way to fight imposter syndrome.

Something else I took away from Dev Academy was a phrase @joshuavial taught us. I repeat it to myself sometimes when I feel  overwhelmed. It's a bit cheesy but if you say it enough you start to believe it :wink: 

> I am good enough, right here, right now, just as I am
