### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [Widdershin/ama#3]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by Widdershin** [comment]
![screenshot](http://i.imgur.com/gr944dS.png)

[dotfiles](https://gist.github.com/Widdershin/a080ec7a6af0f943f40f)

Editor: Neovim + jellybeans theme + lots of plugins
Terminal emulator: iTerm 2
Shell: tmux + zsh
Theme: Modified version of [agnoster](https://gist.github.com/Widdershin/a080ec7a6af0f943f40f) with extra newlines
Font: Sauce Code Powerline

I generally customize my tmux layout on a per project basis. This is relatively standard though. I make heavy use of tmux sessions, generally one per project. I use [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect) to persist my environment so I never have to spend time setting up my console.

Here's my current session list:

![sessions](http://i.imgur.com/oqxuJ9C.png)

I use a hotkey window (guake style) setup in iTerm 2, that allows me to toggle a fullscreen terminal with one button press. I find this essential for working on a laptop. At work, I have 2 extra screens, so I have a dedicated terminal screen and then toggle another if needed.

I make heavy use of sending commands from vim to tmux to drive tests while I work. I love the flexibility afforded using all terminal components.
