### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [Widdershin/ama#4]

**Comment by Widdershin** [comment]
I got my start in programming through making games, when I was maybe 11. I used Game Maker, originally using the drag and drop tile interface until one day I found a guide that translated tiles into the equivalent code in GML (game maker language). I suddenly realized that I could program!

I recently uploaded a large portion of the games I made during this period [to my Github](https://github.com/Widdershin/old-game-maker-games/), if anyone wants to see.

I spent 3 or 4 years just making games in Game Maker, and then I did the first year of university computer science during my last year of high school, where I learned Python and a decent basis in algorithms.

I quickly realized that while I loved learning, academia was just not the place for me. I started working in software (not as a developer) but I would write code during my downtime. I started getting interested in the web, which lead to me attending a coding bootcamp and starting my current career as a web developer.
