### ISSUE TITLE
What thing you made are you most proud of?

### ISSUE THREAD

**Issue by sindresorhus** [Widdershin/ama#5]

**Comment by Widdershin** [comment]
This is a really challenging question for me. I don't have any coding accomplishments that really stand out (from my point of view), but here goes:

I think I'm probably most proud of my current project, [Helix Pi](http://helix-pi.net/). It's a tool to enable anyone to make games without having to write code. I've been working on it for 3 months straight now. I've never had this level of passion or motivation for a side project before, which is cool. Helix Pi still doesn't really work yet, but it can make programs with basic behaviors.

Runners up:
- [Questling](http://indiegames.com/2011/06/freeware_game_pick_questling_f.html), a Ludum Dare game I made in 2011
- [Pixel Story](http://ludumdare.com/compo/ludum-dare-23/?action=preview&uid=2581), a Ludum Dare game from 2012
- The work I've done as a moderator for the /r/longboarding community, including building [an automated system for community reviews](http://reviews.rlongboarding.com/)
- [Railsn00bs](http://www.meetup.com/WellingtonRailsn00bs/), a meetup for helping anyone and everyone learn to code that I co-organize
