### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by aarroyoc** [Widdershin/ama#6]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by Widdershin** [comment]
I have to say I know very little about Spain.

Things I do know/come to mind:
- High youth unemployment rate
- Apparently Barcelona is a great city to visit
- Soccer, of course
- Tapas are amazing
- I imagine the weather in Spain is lovely for some reason
- Spain is literally on the opposite side of the world from New Zealand, where I live. If I dug straight down, I would hit Spain

I would love to visit someday.
