### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [Widdershin/ama#9]

**Comment by Widdershin** [comment]
Yeah, I do!

I help organize a meetup group, [Railsn00bs](http://www.meetup.com/WellingtonRailsn00bs/). A bunch of us get together every three weeks and learn about all things webby/rails.

My employer, Powershop, also has a training team called the Dev Train where all new developers (regardless of seniority) spend up to three months learning about Ruby, Rails and writing beautiful code. As of late, 50% of my work has been running the Dev Train. I really enjoy how much time I get to spend pairing and working to help others learn.

I also help any of my friends who are learning to code. Recently I've been doing Cycle.js stuff with @stevenmatthews.
